Test wind data COASTGUARD

In [2]:
import numpy as np
import pandas as pd

In [27]:
wf = pd.read_csv(r'./data/wind_test_front.csv',header=None)
wl = pd.read_csv(r'./data/wind_test_left.csv',header=None)
# wr = pd.read_csv(r'./data/wind_test_right.csv')

In [47]:
fromfront = wf.dropna()
fromfront.columns =['a', 'b', 'u', 'v','w','c','d','e','f']
fromfront

fromleft = wl.dropna()
fromleft.columns =['a', 'b', 'u', 'v','w','c','d','e','f']
fromleft

,a,b,u,v,w,c,d,e,f
0,"data: ""1517156375.07",\x02P,-002.149,-004.998,+000.369,M,+026.67,00,"\x030A\r\n"""
2,"data: ""1517156375.17",\x02P,-000.619,-001.549,-001.428,M,+026.72,00,"\x030E\r\n"""
4,"data: ""1517156375.27",\x02P,-001.658,-002.351,-001.391,M,+026.47,00,"\x0305\r\n"""
6,"data: ""1517156375.37",\x02P,-002.518,-002.650,-001.502,M,+026.67,00,"\x030B\r\n"""
8,"data: ""1517156375.47",\x02P,-000.546,-004.019,-000.653,M,+026.50,00,"\x030D\r\n"""
...,...,...,...,...,...,...,...,...,...
810,"data: ""1517156415.57",\0\x02P,+000.086,-005.192,-001.364,M,+026.48,00,"\x0308\r\n"""
812,"data: ""1517156415.67",\x02P,-000.944,-0\006.009,+000.760,M,+026.98,00,"\x0303\r\n"""
814,"data: ""1517156415.77",\x02P,-000.799,-005.677,-002.37\07,M,+027.10,00,"\x0306\r\n"""
816,"data: ""1517156415.87",\x02P,+000.428,-006.155,-000.359,M,+026.76,00\0,"\x0302\r\n"""
818,"data: ""1517156415.97",\x02P,-001.652,-007.192,-001.523,M,+027.22,00,"\x030A\r\n"""

In [49]:
fromleft["u"] = pd.to_numeric(fromleft["u"], downcast="float")

ValueError: Unable to parse string "-002\0.875" at position 96

In [50]:
fromleft[90:100]

,a,b,u,v,w,c,d,e,f
180,"data: ""1517156384.07",\x02P,-000.383,-004.545,-001.477,M,+026.71,00,"\x0308\r\n"""
182,"data: ""1517156384.17",\x02P,-002.673,-003.647,-002.007,M,+026.72,00,"\x0305\r\n"""
184,"data: ""1517156384.27",\x02P,-002.357,-004.399,-000.807,M,+026.36,00,"\x030D\r\n"""
186,"data: ""1517156384.37",\x02P,-003.713,-002.972,-002.257,M,+026.52,00,"\x030E\r\n"""
188,"data: ""1517156384.47",\x02P,+000.134,-004.428,-001.050,M,+026.31,00,"\x030F\r\n"""
190,"data: ""1517156384.57",\x02P,-002.506,-003.335,+000.289,M,+026.66,00,"\x0301\r\n"""
192,"data: ""1517156384.67",\x02P,-002\0.875,-003.971,-000.956,M,+026.83,00,"\x0306\r\n"""
194,"data: ""1517156384.77",\x02P,-002.305,-004.266,\0-001.084,M,+026.48,00,"\x0300\r\n"""
196,"data: ""1517156384.87",\x02P,-001.319,-001.851,-001.709,M,+02\06.55,00,"\x030B\r\n"""
198,"data: ""1517156384.97",\x02P,-002.380,-001.345,-000.447,M,+026.59,00,"\x0302\r\n"""