Test wind data COASTGUARD

In [3]:
import numpy as np
import pandas as pd

In [4]:
wf = pd.read_csv(r'./data/wind_test_front.csv',header=None)
wl = pd.read_csv(r'./data/wind_test_left.csv',header=None)
# wr = pd.read_csv(r'./data/wind_test_right.csv')

In [5]:
fromfront = wf.dropna()
fromfront.columns =['a', 'b', 'u', 'v','w','c','d','e','f']
fromfront

fromleft = wl.dropna()
fromleft.columns =['a', 'b', 'u', 'v','w','c','d','e','f']
fromleft

,a,b,u,v,w,c,d,e,f
0,"data: ""1517156375.07",\x02P,-002.149,-004.998,+000.369,M,+026.67,00,"\x030A\r\n"""
2,"data: ""1517156375.17",\x02P,-000.619,-001.549,-001.428,M,+026.72,00,"\x030E\r\n"""
4,"data: ""1517156375.27",\x02P,-001.658,-002.351,-001.391,M,+026.47,00,"\x0305\r\n"""
6,"data: ""1517156375.37",\x02P,-002.518,-002.650,-001.502,M,+026.67,00,"\x030B\r\n"""
8,"data: ""1517156375.47",\x02P,-000.546,-004.019,-000.653,M,+026.50,00,"\x030D\r\n"""
...,...,...,...,...,...,...,...,...,...
810,"data: ""1517156415.57",\0\x02P,+000.086,-005.192,-001.364,M,+026.48,00,"\x0308\r\n"""
812,"data: ""1517156415.67",\x02P,-000.944,-0\006.009,+000.760,M,+026.98,00,"\x0303\r\n"""
814,"data: ""1517156415.77",\x02P,-000.799,-005.677,-002.37\07,M,+027.10,00,"\x0306\r\n"""
816,"data: ""1517156415.87",\x02P,+000.428,-006.155,-000.359,M,+026.76,00\0,"\x0302\r\n"""
818,"data: ""1517156415.97",\x02P,-001.652,-007.192,-001.523,M,+027.22,00,"\x030A\r\n"""

In [6]:
fromfront

,a,b,u,v,w,c,d,e,f
0,"data: ""1517156250.07",\x02P,-4.758,0.539,-1.085,M,26.57,0.0,"\x030A\r\n"""
2,"data: ""1517156250.17",\x02P,-7.897,1.043,-0.643,M,26.93,0.0,"\x0309\r\n"""
4,"data: ""1517156250.27",\x02P,-2.772,-0.652,-2.691,M,26.72,0.0,"\x030B\r\n"""
6,"data: ""1517156250.37",\x02P,-2.593,0.189,-0.978,M,27.05,0.0,"\x030A\r\n"""
8,"data: ""1517156250.47",\x02P,-3.764,-0.338,-0.667,M,26.47,0.0,"\x0309\r\n"""
...,...,...,...,...,...,...,...,...,...
400,"data: ""1517156270.07",\x02P,-6.109,-0.087,-1.176,M,26.88,0.0,"\x0303\r\n"""
402,"data: ""1517156270.17",\x02P,-3.748,-1.519,-1.491,M,26.52,0.0,"\x030D\r\n"""
404,"data: ""1517156270.27",\x02P,-3.19,-0.643,-1.827,M,26.55,0.0,"\x0305\r\n"""
406,"data: ""1517156270.37",\x02P,-4.714,0.775,-2.195,M,26.59,0.0,"\x0305\r\n"""
408,"data: ""1517156270.47",\x02P,-2.8,0.469,-1.963,M,26.47,0.0,"\x030A\r\n"""

In [9]:
df = fromfront
ul = []
for i in range(406):
#     print(i)
    try:
        temp = float(df.u[i:i+1])
    except:
        a =3
#         print(df.u[i:i+1])
#         print(i)
    ul.append(temp)
# fromeleft = fromleft.drop(95)
# fromleft["u"] = pd.to_numeric(fromleft["u"], downcast="float")

In [10]:
np.mean(ul)

-3.5175320197044333